# sonar-scanner.bat ^
#   -D"sonar.projectKey=rshub-hdss" ^
#   -D"sonar.sources=." ^
#   -D"sonar.host.url=https://sonar.savis.vn" ^
#   -D"sonar.login=sqp_bc7b2a2e6fa4c9ebc8db8918b3155bd3113bf9ef"


sonar-scanner.bat -D"sonar.projectKey=bac-a-bank" -D"sonar.sources=." -D"sonar.host.url=https://sonar.savis.vn" -D"sonar.login=sqp_28e43307dc0f4436f1c47087b9de9cc2672976e6"